# Generated by Django 4.0.6 on 2022-08-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='ulr',
            new_name='url',
        ),
    ]
